tasks/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# from tasks.views import TaskView
from tasks.views import *


urlpatterns = [
    #url(r'', TaskView.as_view(), name='task'),
    url(r'^public_tasks/$', public_tasks, name='public'),
    url(r'^public_my_tasks/$', public_my_tasks, name='public_my'),
    url(r'^private_tasks/$', private_tasks, name='private_tasks'),
    url(r'^update_task/(?P<id>[0-9]+)/$', update_task, name='update_task'),
    url(r'^delete_task/(?P<id>[0-9]+)/$', delete_task, name='delete_task'),
    url(r'', task_all, name='home'),
    # url(r'', TaskView.as_view(), name='home'),

]

zavdannia/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from profiles.views import base_page
# from tasks.views import TaskView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('tasks.urls', namespace='tasks')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
elif not settings.PRODUCTION:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
import os
from django.conf import settings
import uuid


# Create your models here.

STATUS_CHOICES = (
    ('1', 'open'),
    ('2', 'processing'),
    ('3', 'closed'),
    )
TASK_STATUS = (
    ('1', 'public'),
    ('2', 'private'),
)



def get_file_path(self, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join(self.folder_name, self.user_name, filename)


class UserFiles(models.Model):
    file = models.FileField(blank=True, null=True, upload_to=get_file_path)
    date_of_add = models.DateField(auto_now_add=True, blank=True, null=True)
    name_file = models.CharField(blank=True, null=True, max_length=100)
    relation_to_user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='related_user',
                                         verbose_name='relation to user')

    def __str__(self):
        return str(self.name_file)  # or u''

    @property
    def user_name(self):
        user_name = self.relation_to_user.username
        return user_name

    @property
    def folder_name(self):
        folder = 'user_files'
        return folder


class Task(models.Model):
    title = models.CharField(max_length=120, verbose_name='title task')
    status = models.CharField(max_length=20, blank=True, null=True, default='open', choices=STATUS_CHOICES)
    privacy = models.CharField(max_length=20, blank=True, null=True, default='public', choices=TASK_STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    read = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='updated_by',
                               verbose_name='task author')
    description = models.TextField(max_length=500, blank=True, null=True)
    relation_to_files = models.ManyToManyField(UserFiles, blank=True)

    def relation_to_user_files(self):
        return self.relation_to_files.all()

    def __str__(self):
        return str(self.title)  # or u''

tasks/forms.py
from django import forms
from .models import Task, UserFiles, STATUS_CHOICES, TASK_STATUS
from crispy_forms.helper import FormHelper

class TaskForm(forms.ModelForm):
    title = forms.CharField(label='task_title',required=True)
    description = forms.CharField(label='description of task', widget=forms.TextInput)
    status = forms.CharField(max_length=20, widget=forms.Select(choices=STATUS_CHOICES))
    privacy = forms.CharField(max_length=20, widget=forms.Select(choices=TASK_STATUS))

    class Meta:
        model = Task
        fields = ['title','description', 'status', 'privacy']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        check_task_title = Task.objects.filter(title=title)
        if check_task_title.exists():
            raise forms.ValidationError("email is already exists")
        else:
            return title

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = u'title*'
        self.fields['title'].label = ''
        self.fields['description'].widget.attrs['placeholder'] = u'description'
        self.fields['description'].label = ''
        self.fields['status'].widget.attrs['placeholder'] = u'status'
        self.fields['status'].label = 'choose your status'
        self.fields['privacy'].widget.attrs['placeholder'] = u'privacy'
        self.fields['privacy'].label = 'privacy of task'

tasks/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseRedirect, HttpResponse
from .forms import TaskForm
from .models import Task
from django.contrib import messages
from django.core.urlresolvers import reverse
from events_task.events import EventManager
from profiles.mailing import send_email
# Create your views here.


def public_tasks(request, *args, **kwargs):
    if request.user.is_authenticated:
        tasks_objects = Task.objects.all()
        return render(request, 'public_tasks.html', {'task': tasks_objects})
    return HttpResponse({"error": "you need to be authen..."}, status=400)


def public_my_tasks(request, *args, **kwargs):
    if request.user.is_authenticated:
        tasks_objects = Task.objects.filter(privacy='1', author=request.user)
        if tasks_objects:
            return render(request, 'public_tasks.html', {'task': tasks_objects})
        else:
            return HttpResponse({"error": "no data to show..."}, status=400)
    return HttpResponse({"error": "you need to be authen..."}, status=400)


def private_tasks(request, *args, **kwargs):
    tasks_objects = Task.objects.filter(privacy='2', author=request.user)
    context = {
        'form': TaskForm,
        'task': tasks_objects,
        }
    if request.method == "POST":
        form = TaskForm(request.POST or None)
        if form.is_valid():
            form.save(commit=False)
            messages.success(request, 'OK')
            event = EventManager(type='task',
                                 action='update',
                                 event_mark=form.cleaned_data.get('id'),
                                 author=request.user,
                                 recepient=[request.user],  # recipient is need then anybody must events
                                 url='',
                                 string='new task created %s' % form.cleaned_data.get('title')
                                 )
            event.event_create()
            send_email.delay({'username': str(request.user.username),
                              'user_email': str(request.user.email),
                              'prefix': 'task_update',
                              'source': 'task_mail',
                              'sender': str(request.user.username)})
            messages.success(request, 'congrats! your data is saved to db')

            return HttpResponseRedirect('/private_tasks/')
    if tasks_objects:
        return render(request, 'private_tasks.html', context)
    else:
        return HttpResponse({"error": "no data to show..."}, status=400)


def update_task(request, id):
    try:
        task_instance = Task.objects.get(author=request.user, id=id)
    except Task.DoesNotExist as error:
        return HttpResponse({'error': str(error)}, status=400)
    if request.method == 'POST':
        form = TaskForm(request.POST or None, instance=task_instance)
        if form.is_valid():
            form_task = form.save(commit=False)
            form.author = request.user
            form_task.read = False
            event = EventManager(type='task',
                                 action='update',
                                 event_mark=form.cleaned_data.get('id'),
                                 author=request.user,
                                 recepient=[request.user],  # recipient is need then anybody must events
                                 url='',
                                 string='new task created %s' % form.cleaned_data.get('title')
                                 )
            event.event_create()
            send_email.delay({'username': str(request.user.username),
                              'user_email': str(request.user.email),
                              'prefix': 'task_create',
                              'source': 'task_mail',
                              'sender': str(request.user.username)})
            form_task.save()
            messages.success(request, 'task {task_titile} updated successfully'.format(task_titile=form_task.id))


def delete_task(request, id):
    try:
        task_instance = Task.objects.get(author=request.user, id=id)
    except Task.DoesNotExist as error:
        return HttpResponse({'error': str(error)}, status=400)
    task_instance.delete()
    event = EventManager(type='task',
                         action='update',
                         event_mark=task_instance.id,
                         author=request.user,
                         recepient=[request.user],  # recipient is need then anybody must events
                         url='',
                         string='new task created %s' % task_instance.title
                         )
    event.event_create()
    messages.warning(request, 'deleted successfully')
    return HttpResponseRedirect('/private_tasks/')


def task_all(request):
    if request.user.is_authenticated:
        tasks_objects = Task.objects.all()
    else:
        tasks_objects = Task.objects.filter(privacy='1')
    if request.method == 'GET':
        context = {
            'task': tasks_objects,
            'form': TaskForm,
        }
        return render(request, 'tasks.html', context=context)
    if request.method == "POST":
        if request.user.is_authenticated:
            form = TaskForm(request.POST or None)
            if form.is_valid():
                sav_form = form.save(commit=False)
                sav_form.author = request.user
                sav_form.save()
                event = EventManager(type='task',
                                     action='create',
                                     event_mark=form.cleaned_data.get('id'),
                                     author= request.user,
                                     recepient=[request.user],  #recipient is need then anybody must events
                                     url='',
                                     string='new task created %s' % form.cleaned_data.get('title')
                                    )
                event.event_create()
                send_email.delay({'username': str(request.user.username),
                                                      'user_email': str(request.user.email),
                                                      'prefix': 'task_create',
                                                      'source': 'task_mail',
                                                      'sender': str(request.user.username)})
                print('done')
                # except OSError:
                #     return HttpResponse('shit happens, check your mail backend settings')
                messages.success(request, 'congrats! your data is saved to db')
                # add mailing
                return HttpResponseRedirect('/task/')
        return HttpResponseRedirect('/home/')

# class TaskView(View):
#     form = TaskForm
#
#     def get(self, request, *args, **kwargs):
#         print('METHOD GET')
#         # rensder all users tasks
#         if request.user.is_authenticated:
#             user_task = Task.objects.all()
#         context = {
#             'task': user_task,
#             'form': self.form
#
#         }
#         return render(request, 'private_tasks.html', context=context)
#
#     def post(self, request, *args, **kwargs):
#         print('METHOD POST')
#         form = self.form(request.POST or None)
#         if form.is_valid():
#             sav_form = form.save(commit=False)
#             sav_form.author = request.user
#             sav_form.save()
#             message = messages.success(request, 'congrats! your data is saved to db')
#             return HttpResponseRedirect('/task/')
#         else:
#             return render(request, 'home.html', {'from': self.form})

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}

    {%  include 'head_css.html' %}
    {%  include 'body_css.html' %}

    {% endblock %}

    <style>
        {%  block style %}

        {% endblock %}
    </style>

  </head>
  <body>

  {%  include 'navbar.html' %}

  {% block body %}

        {% block content %}
        {% endblock %}


  {% endblock %}

    {% block extra_body %}
    {% endblock %}

{% include 'javascript.html' %}
  </body>
</html>

templates/body_css.html
{% load static %}
<link rel="stylesheet" href="../static/css/bootstrap.min.css">

<link rel="stylesheet" href="../static/css/body_css.css">
<link rel="stylesheet" href="../static/css/font-awesome-4.7.0/css/font-awesome.min.css">

templates/head_css.html
{%  load static %}
<link  href="../static/css/bootstrap.min.css" rel="stylesheet">

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container ">
            <div class="row">
            <div class="col-sm-offset-2"></div>
        {% if messages %}
            <div class="alert alert-success home_message" role="alert">
             <strong>Messages:</strong>
            <ul>
            {% for message in messages %}
            <li>{{message}}</li>
            {% endfor %}
              </ul>
            </div>
        {% endif %}
        </div>
    </div>



{% if request.user.is_authenticated %}
    <span class="label label-default"><i class="fa fa-user-o" aria-hidden="true"></i> User {{ request.user }} tasks</span>
{% endif %}


    {% block tasks %}

   {% endblock tasks %}


{%  if request.user.is_authenticated %}
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" id="add_task_button">
  <i class="fa fa-tasks" aria-hidden="true"></i>
    add new task
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
         <form action="." method="post">
        {% csrf_token %}
            {{ form|crispy }}
      <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Submit">
      </div>
        </form>
      </div>
    </div>
  </div>
</div>
{%  endif %}
{% endblock body %}


{% block content %}

{% endblock %}

templates/javascript.html
{%  load static %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src="{% static 'js/for_modal.js' %}"></script>

templates/modal_about.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

templates/navbar.html
<nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=".">TEST TASK</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'tasks:home' %}">Home</a></li>


{#            <li><a href="{% url 'newsletter:contact' %}">Contact</a></li>#}
            {% if user.is_authenticated %}
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">task manager <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'tasks:public' %}" id="public_tasks">See all public tasks</a></li>
                <li><a href="{% url 'tasks:public_my' %}" id="private_tasks" >See my public tasks</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Privacy menu</li>
                <li><a href="{% url 'tasks:private_tasks' %}">See my private tasks</a></li>
              </ul>
            </li>
              {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}

            <li> <button type="button " class="btn btn-default navbar-btn"><a href="{% url 'account_email' %}">Change E-mail</a></button></li>
            <li> <button type="button " class="btn btn-default navbar-btn"><a href="{% url 'account_logout' %}">Sign Out</a></button></li>
            {% else %}
            <li><button type="button " class="btn btn-default navbar-btn"><a href="{% url 'account_login' %}">Sign In</a></button></li>
            <li><button type="button " class="btn btn-default navbar-btn"><a href="{% url 'account_signup' %}">Sign Up</a></button></li>
          {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/private_tasks.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block tasks %}
     <div class="container">
        <div class="row">
            <div class="col-sm-8 kanban-tasks">
                  {% for tasker in task %}
                  <div class="col-sm-4">

                      <button type="button" class="btn btn-primary btn-lg update_button" data-toggle="modal" data-target="#myModal">
                          <i class="fa fa-pencil-square-o pull-right fa-2x" aria-hidden="true"></i>
                      </button>
                        <!-- Modal -->
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                              </div>
                              <div class="modal-body">
                                 <form action="." method="post">
                                {% csrf_token %}
                                    {{ form|crispy }}
                              <div class="modal-footer">
                                  <a href="/update_task/{{ tasker.id }}/"><input class="btn btn-default" type="submit" value="Submit"></a>
                              </div>
                                </form>
                              </div>
                            </div>
                          </div>
                        </div>


{#                      <p class="list-group-item">#}
                       <button type="button" class="btn btn-primary btn-lg delete_button">

                           <a href="/delete_task/{{ tasker.id }}/"><i class="fa fa-eraser fa-2x" aria-hidden="true"></i></a>

                       </button>
{#                      </p>#}


                      <p class="list-group-item" id="task_title"><i class="fa fa-tasks" aria-hidden="true"></i>
                           Title: {{ tasker.title }}</p>
                      <p class="list-group-item">Description: {{ tasker.description }}</p>
                      <p class="list-group-item">Staus: {{ tasker.get_status_display }} </p>
                      <p class="list-group-item"><strong>Privacy: {{ tasker.get_privacy_display }}</strong> </p>
                  </br >
                  </div>
                  {% endfor %}
            </div>

{% endblock tasks %}

templates/public_tasks.html
{% extends 'home.html' %}

{% block tasks %}
     <div class="container">
        <div class="row">
            <div class="col-sm-8 kanban-tasks">
                  {% for tasker in task %}
                  <div class="col-sm-4">
                      <p class="list-group-item" id="task_title"><i class="fa fa-tasks" aria-hidden="true"></i>
                           Title: {{ tasker.title }}</p>
                      <p class="list-group-item">Description: {{ tasker.description }}</p>
                      <p class="list-group-item">Staus: {{ tasker.get_status_display }} </p>
                      <p class="list-group-item"><strong>Privacy: {{ tasker.get_privacy_display }}</strong> </p>
                  </br >
                  </div>
                  {% endfor %}
            </div>

{% endblock tasks %}

templates/tasks.html
{#{%  extends 'base.html' %}#}
{#    {% block body %}#}
{#        {% block tasks %}#}
{#        <div class="list-group">#}
{#         {%  for task in task %}#}
{#             <a href="#" class="list-group-item">{{ task.title }}</a>#}
{#        </div>#}
{#        {% endfor %}#}
{##}
{#    {% endblock tasks %}#}
{#    {% endblock body %}#}

{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block tasks %}
      <div class="container">
        <div class="row">
            <div class="col-sm-8 kanban-tasks">
                  {% for tasker in task %}
                  <div class="col-sm-4">
                      <p class="list-group-item" id="task_title">Title: {{ tasker.title }}</p>
                      <p class="list-group-item">Description: {{ tasker.description }}</p>
                      <p class="list-group-item">Staus: {{ tasker.get_status_display }} </p>
                  </br >
                  </div>
                  {% endfor %}
            </div>


{% endblock tasks %}

templates/test.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="." method="post">
        {% csrf_token %}
     {{ form|crispy }}
      <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Submit">
      </div>
        </form>
</body>
</html>